services:
  api:
    build: .
    env_file:
      - .env # Static/build-time vars (already in image, but can be overridden)
      - .env.local # Local/dev secrets or overrides
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  db:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_pass
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

volumes:
  db_data:
