name: RELEASE

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install


      - name: Bump version and generate changelog
        env:
          CI: true
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: poetry run release version

      - name: Build package
        run: poetry build

      - name: Publish release
        env:
          CI: true
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: poetry run release publish
